import { describe, expect, it } from 'vitest'
import { existsSync, readFileSync } from 'node:fs'
import { resolve } from 'node:path'

describe('public agent square', () => {
  it('registers a square-only public route surface separate from dashboard routes', () => {
    const routerSource = readFileSync(resolve(process.cwd(), 'src/router/index.js'), 'utf8')
    const appSource = readFileSync(resolve(process.cwd(), 'src/App.vue'), 'utf8')

    expect(routerSource).toContain('isSquareBase')
    expect(routerSource).toContain("createWebHistory(isSquareBase ? '/square' : '/dashboard')")
    expect(routerSource).toContain("name: 'PublicSquare'")
    expect(routerSource).toContain("component: () => import('../views/PublicSquare.vue')")
    expect(routerSource).toContain('const squareRoutes')
    expect(routerSource).toContain('const dashboardRoutes')
    expect(appSource).toContain("const chatRouteNames = new Set(['AgentChat', 'BuiltinAgent', 'PublicAgent'])")
  })

  it('renders the public square from a dedicated page and opens public agents without share tokens', () => {
    const squarePath = resolve(process.cwd(), 'src/views/PublicSquare.vue')
    expect(existsSync(squarePath)).toBe(true)
    const squareSource = readFileSync(squarePath, 'utf8')
    const apiSource = readFileSync(resolve(process.cwd(), 'src/api/index.js'), 'utf8')

    expect(squareSource).toContain('publicSquareApi.list')
    expect(squareSource).toContain('router.push({')
    expect(squareSource).toContain("name: 'PublicAgent'")
    expect(squareSource).not.toContain('workflow.share_token')
    expect(squareSource).toContain('public-square-grid')
    expect(apiSource).toContain('export const publicSquareApi')
    expect(apiSource).toContain("publicApi.get('/public/square/workflows'")
  })

  it('adds a workflow setting for publishing public-share agents to the square', () => {
    const configSource = readFileSync(resolve(process.cwd(), 'src/views/WorkflowConfig.vue'), 'utf8')
    const zh = readFileSync(resolve(process.cwd(), 'src/locales/zh-CN.js'), 'utf8')
    const en = readFileSync(resolve(process.cwd(), 'src/locales/en-US.js'), 'utf8')

    expect(configSource).toContain('workflowForm.publish_to_square')
    expect(configSource).toContain('workflowForm.api_published')
    expect(configSource).toContain('workflowConfig.workflow.publishToSquare')
    expect(configSource).toContain('workflowConfig.workflow.apiPublished')
    expect(configSource).toContain(':disabled="isBuiltinWorkflow || !workflowForm.public_share_enabled"')
    expect(configSource).toContain('onPublicShareChanged')
    expect(zh).toContain('publishToSquare')
    expect(en).toContain('publishToSquare')
  })

  it('wires public multi-user room APIs, tokens, and room route state', () => {
    const apiSource = readFileSync(resolve(process.cwd(), 'src/api/index.js'), 'utf8')
    const publicAgentSource = readFileSync(resolve(process.cwd(), 'src/views/PublicAgent.vue'), 'utf8')
    const appSource = readFileSync(resolve(process.cwd(), 'src/App.vue'), 'utf8')

    expect(apiSource).toContain('export const publicRoomsApi')
    expect(apiSource).toContain('/public/workflows/${encodeURIComponent(workflowId)}/rooms')
    expect(apiSource).toContain('/public/rooms/${encodeURIComponent(roomId)}/session')
    expect(apiSource).toContain('/public/rooms/${encodeURIComponent(roomId)}/bootstrap')
    expect(apiSource).toContain('/public/rooms/${encodeURIComponent(roomId)}/join')
    expect(apiSource).toContain('/public/rooms/${encodeURIComponent(roomId)}/state')
    expect(apiSource).toContain('/public/rooms/${encodeURIComponent(roomId)}/events')
    expect(apiSource).toContain('/public/rooms/${encodeURIComponent(roomId)}/typing')
    expect(apiSource).toContain('/public/rooms/${encodeURIComponent(roomId)}/chat')
    expect(apiSource).toContain('/public/rooms/${encodeURIComponent(roomId)}/run')
    expect(apiSource).toContain("'X-AgentClaw-Room-Token'")
    expect(apiSource).toContain('withCredentials: true')
    expect(publicAgentSource).toContain('route.query.room_id')
    expect(publicAgentSource).toContain('route.query.room_token')
    expect(publicAgentSource).toContain('public-room-id')
    expect(publicAgentSource).toContain('public-room-token')
    expect(publicAgentSource).toContain('delete query.room_token')
    expect(appSource).toContain('delete query.room_token')
  })

  it('keeps public room chat isolated from normal public runs and hides process state', () => {
    const source = readFileSync(resolve(process.cwd(), 'src/views/AgentChat.vue'), 'utf8')
    const messageSource = readFileSync(resolve(process.cwd(), 'src/components/chat/ChatMessage.vue'), 'utf8')

    expect(source).toContain('publicRoomsApi')
    expect(source).toContain('publicRoomId')
    expect(source).toContain('publicRoomToken')
    expect(source).toContain('isPublicRoomMode')
    expect(source).toContain('createPublicRoom')
    expect(source).toContain('joinPublicRoom')
    expect(source).toContain('startPublicRoomPolling')
    expect(source).toContain('stopPublicRoomPolling')
    expect(source).toContain('submitPublicRoomTyping')
    expect(source).toContain('applyPublicRoomState')
    expect(source).toContain('runPublicRoomMessage')
    expect(source).toContain('if (this.isPublicRoomMode) return false')
    expect(source).toContain('publicRoomsApi.run')
    expect(source).toContain('publicRoomsApi.typing')
    expect(source).toContain('publicRoomsApi.listChat')
    expect(source).toContain('publicRoomsApi.sendChat')
    expect(source).toContain('startPublicRoomEvents')
    expect(source).toContain('stopPublicRoomEvents')
    expect(source).toContain('handlePublicRoomEvent')
    expect(source).toContain("new EventSource(publicRoomsApi.eventsUrl(this.publicRoomId, baseUrl))")
    expect(source).toContain("case 'agent_message_delta'")
    expect(source).toContain('appendPublicRoomStreamingDelta')
    expect(source).toContain('sendPublicRoomChatMessage')
    expect(source).toContain('public-room-player-chat')
    expect(source).toContain('@mousedown.prevent="startPublicRoomChatDrag"')
    expect(source).toContain('@touchstart.passive="startPublicRoomChatDrag"')
    expect(source).not.toContain('v-html="message.content"')
    expect(source).toContain('publicRoomShareLink')
    expect(messageSource).toContain('userDisplayName')
    expect(messageSource).toContain('isPublicRoomParticipantMessage')
    expect(messageSource).toContain('!msg.isInterruptResponse && !isPublicRoomParticipantMessage')
  })
})
