import { describe, expect, it } from 'vitest'
import { readFileSync } from 'node:fs'
import { resolve } from 'node:path'

describe('model config settings UX', () => {
  it('exposes a system settings form for models.json hot updates', () => {
    const settingsSource = readFileSync(resolve(process.cwd(), 'src/views/Settings.vue'), 'utf8')
    const apiSource = readFileSync(resolve(process.cwd(), 'src/api/index.js'), 'utf8')
    const zh = readFileSync(resolve(process.cwd(), 'src/locales/zh-CN.js'), 'utf8')
    const en = readFileSync(resolve(process.cwd(), 'src/locales/en-US.js'), 'utf8')
    const zhModelConfig = zh.match(/modelConfig: \{\n      title: '模型配置',[\s\S]*?\n    \},\n    envSections:/)?.[0] || ''
    const enModelConfig = en.match(/modelConfig: \{\n      title: 'Model Config',[\s\S]*?\n    \},\n    envSections:/)?.[0] || ''

    expect(settingsSource).toContain('name="models"')
    expect(settingsSource).toContain('fetchModelsConfig')
    expect(settingsSource).toContain('saveModelsConfig')
    expect(settingsSource).toContain('modelEditorVisible')
    expect(settingsSource).toContain('openModelEditor')
    expect(settingsSource).toContain('saveModelEditor')
    expect(settingsSource).toContain('removeModelConfig')
    expect(settingsSource).toContain('modelsConfigForm.models')
    expect(settingsSource).toContain(':options="modelSelectOptions"')
    expect(settingsSource).toContain('settingsApi.getModelsConfig')
    expect(settingsSource).toContain('settingsApi.updateModelsConfig')
    expect(settingsSource).toContain("model.api_key === MODEL_SECRET_MASK ? ''")
    expect(settingsSource).toContain('payload.api_key = MODEL_SECRET_MASK')
    expect(settingsSource).toContain('supports_vision')
    expect(settingsSource).toContain('visionModelSelectOptions')
    expect(settingsSource).toContain("speech2text: ''")
    expect(settingsSource).toContain("tts: ''")
    expect(settingsSource).toContain("tts_voice: ''")
    expect(settingsSource).toContain("'speech2text'")
    expect(settingsSource).toContain("'tts'")
    expect(settingsSource).toContain('settings.modelConfig.speech2TextModel')
    expect(settingsSource).toContain('settings.modelConfig.ttsModel')
    expect(settingsSource).toContain('settings.modelConfig.ttsVoice')
    expect(settingsSource).toContain('modelEditorForm.voice')
    expect(settingsSource).toContain('modelEditorForm.audio_format')
    expect(settingsSource).toContain('modelEditorForm.supported_file_extensions')
    expect(settingsSource).toContain("!['embedding', 'rerank', 'speech2text', 'tts'].includes(model.type)")
    expect(settingsSource).not.toContain("{ label: 'vision', value: 'vision' }")
    expect(settingsSource).not.toContain('settings.modelConfig.apiKeySet')
    expect(settingsSource).not.toContain('settings.modelConfig.apiKeyUnset')
    expect(settingsSource).not.toContain("settings.modelConfig.temperature")
    expect(settingsSource).not.toContain("settings.modelConfig.maxTokens")
    expect(settingsSource).not.toContain("settings.modelConfig.timeout")
    expect(apiSource).toContain('getModelsConfig')
    expect(apiSource).toContain('updateModelsConfig')
    expect(zh).toContain('模型配置')
    expect(zh).toContain('热更新')
    expect(zh).toContain('编辑模型')
    expect(zh).toContain('支持视觉')
    expect(zh).toContain('默认 ASR 模型')
    expect(zh).toContain('默认 TTS 模型')
    expect(zhModelConfig).not.toContain('apiKeySet:')
    expect(zhModelConfig).not.toContain('apiKeyUnset:')
    expect(zhModelConfig).not.toContain('temperature:')
    expect(zhModelConfig).not.toContain('maxTokens:')
    expect(zhModelConfig).not.toContain('timeout:')
    expect(en).toContain('Model Config')
    expect(en).toContain('hot reload')
    expect(en).toContain('Edit model')
    expect(en).toContain('Supports vision')
    expect(en).toContain('Default ASR model')
    expect(en).toContain('Default TTS model')
    expect(enModelConfig).not.toContain('apiKeySet:')
    expect(enModelConfig).not.toContain('apiKeyUnset:')
    expect(enModelConfig).not.toContain('temperature:')
    expect(enModelConfig).not.toContain('maxTokens:')
    expect(enModelConfig).not.toContain('timeout:')
  })

  it('excludes ASR and TTS models from conversation model selectors', () => {
    const utilSource = readFileSync(resolve(process.cwd(), 'src/utils/models.js'), 'utf8')

    expect(utilSource).toContain("'speech2text'")
    expect(utilSource).toContain("'tts'")
    expect(utilSource).toContain('speech2text|tts')
  })

  it('scopes model channels by model type in the editor', () => {
    const settingsSource = readFileSync(resolve(process.cwd(), 'src/views/Settings.vue'), 'utf8')

    expect(settingsSource).toContain('modelChannelVisible')
    expect(settingsSource).toContain('currentModelChannelOptions')
    expect(settingsSource).toContain('MODEL_TYPES_WITHOUT_CHANNEL')
    expect(settingsSource).toContain("new Set(['embedding', 'rerank'])")
    expect(settingsSource).toContain('CHAT_MODEL_CHANNEL_OPTIONS')
    expect(settingsSource).toContain('AUDIO_MODEL_CHANNEL_OPTIONS')
    expect(settingsSource).toContain("['speech2text', 'tts'].includes(type)")
    expect(settingsSource).toContain("v-if=\"modelChannelVisible\"")
    expect(settingsSource).toContain(':options="currentModelChannelOptions"')
    expect(settingsSource).toContain('normalizeModelEditorForType')
    expect(settingsSource).toContain('@update:value="handleModelTypeChange"')
    expect(settingsSource).toContain("delete payload.channel")
  })
})
