<template>
  <div>
    <!-- Header -->
    <div class="detail-header">
      <div class="detail-header-left">
        <button class="back-btn" @click="router.push(`/knowledgebases/${route.params.id}`)">
          <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M19 12H5"/><path d="M12 19l-7-7 7-7"/></svg>
        </button>
        <h2 class="detail-title">{{ document.name }}</h2>
        <span class="chunk-count-badge">{{ t('knowledgebaseDocumentDetail.chunkCount', { count: chunks.length }) }}</span>
      </div>
    </div>

    <!-- Main layout -->
    <div class="doc-layout">
      <!-- Sidebar: chunk list -->
      <aside class="chunk-sidebar">
        <div class="sidebar-header">
          <span class="sidebar-title">{{ t('knowledgebaseDocumentDetail.chunkList') }}</span>
          <button class="add-btn" @click="startChunkEdit()">+ {{ t('knowledgebaseDocumentDetail.newChunk') }}</button>
        </div>
        <div v-if="chunks.length" class="chunk-list">
          <div
            v-for="chunk in pagedChunks" :key="chunk.id"
            :class="['chunk-item', { active: selectedChunkId === chunk.id }]"
            @click="startChunkEdit(chunk)"
          >
            <div class="chunk-item-top">
              <span class="chunk-id">{{ chunk.id }}</span>
              <span v-if="dirtyChunkId === chunk.id" class="dirty-dot"></span>
              <span class="chunk-len">{{ t('knowledgebaseDocumentDetail.characterCount', { count: chunk.length }) }}</span>
            </div>
            <p class="chunk-preview">{{ chunk.preview }}</p>
          </div>
          <n-pagination
            v-if="totalChunkPages > 1"
            v-model:page="chunkPage"
            :page-count="totalChunkPages"
            size="small"
            style="justify-content: center; margin-top: 8px;"
          />
        </div>
        <div v-else class="sidebar-empty">{{ t('knowledgebaseDocumentDetail.noChunks') }}</div>
      </aside>
      <!-- Editor -->
      <div class="chunk-editor">
        <div class="editor-header">
          <div class="editor-title-row">
            <span class="editor-title">{{ selectedChunkId ? t('knowledgebaseDocumentDetail.editChunk') : t('knowledgebaseDocumentDetail.createChunk') }}</span>
            <span :class="['status-badge', isChunkDirty ? 'dirty' : 'synced']">{{ isChunkDirty ? t('knowledgebaseDocumentDetail.unsaved') : (selectedChunkId ? t('knowledgebaseDocumentDetail.synced') : t('knowledgebaseDocumentDetail.creating')) }}</span>
          </div>
          <div class="editor-meta">
            <span class="meta-tag">{{ selectedChunkId ? t('knowledgebaseDocumentDetail.chunkId', { id: chunkDraft.id }) : t('knowledgebaseDocumentDetail.autoGeneratedId') }}</span>
            <span class="char-count">{{ t('knowledgebaseDocumentDetail.characterCount', { count: chunkDraft.content.length }) }}</span>
          </div>
        </div>
        <n-input
          v-model:value="chunkDraft.content"
          type="textarea"
          :placeholder="t('knowledgebaseDocumentDetail.contentPlaceholder')"
          :rows="22"
          class="editor-textarea"
        />
        <div class="editor-footer">
          <n-popconfirm v-if="selectedChunkId" @positive-click="deleteChunk(selectedChunkId)">
            <template #trigger><button class="action-link danger">{{ t('knowledgebaseDocumentDetail.deleteCurrentChunk') }}</button></template>
            {{ t('knowledgebaseDocumentDetail.deleteChunkConfirm') }}
          </n-popconfirm>
          <span v-else />
          <n-button type="primary" size="small" :loading="isSavingChunk" @click="saveChunk">{{ t('knowledgebaseDocumentDetail.saveChunk') }}</n-button>
        </div>
      </div>
    </div>
  </div>
</template>

<script setup>
import { computed, onMounted, ref } from 'vue'
import { useI18n } from 'vue-i18n'
import { useRoute, useRouter } from 'vue-router'
import { NButton, NInput, NPagination, NPopconfirm, useMessage, useDialog } from 'naive-ui'
import { knowledgebaseApi } from '../api'
import { withReadinessRetry } from '../utils/eventualConsistency'

const CHUNKS_PER_PAGE = 8
const route = useRoute()
const router = useRouter()
const message = useMessage()
const dialog = useDialog()
const { t } = useI18n()

const document = ref({ id: route.params.documentId, name: t('knowledgebaseDocumentDetail.documentDefaultName'), status: 'ready' })
const chunks = ref([])
const chunkPage = ref(1)
const selectedChunkId = ref('')
const chunkDraft = ref({ id: '', content: '' })
const draftOriginId = ref('')
const draftOriginContent = ref('')
const isSavingChunk = ref(false)

const isChunkDirty = computed(() => chunkDraft.value.id !== draftOriginId.value || chunkDraft.value.content !== draftOriginContent.value)
const dirtyChunkId = computed(() => isChunkDirty.value ? (selectedChunkId.value || chunkDraft.value.id) : '')
const totalChunkPages = computed(() => Math.max(1, Math.ceil(chunks.value.length / CHUNKS_PER_PAGE)))
const pagedChunks = computed(() => { const start = (chunkPage.value - 1) * CHUNKS_PER_PAGE; return chunks.value.slice(start, start + CHUNKS_PER_PAGE) })
function startChunkEdit(chunk = null) {
  if (isChunkDirty.value) {
    dialog.warning({
      title: t('knowledgebaseDocumentDetail.unsavedChangesTitle'),
      content: t('knowledgebaseDocumentDetail.unsavedChangesContent'),
      positiveText: t('knowledgebaseDocumentDetail.confirm'),
      negativeText: t('knowledgebaseDocumentDetail.cancel'),
      onPositiveClick: () => doStartEdit(chunk),
    })
    return
  }
  doStartEdit(chunk)
}

function doStartEdit(chunk) {
  if (!chunk) { selectedChunkId.value = ''; chunkDraft.value = { id: '', content: '' }; draftOriginId.value = ''; draftOriginContent.value = ''; return }
  selectedChunkId.value = chunk.id; syncChunkPage(chunk.id)
  chunkDraft.value = { ...chunk }; draftOriginId.value = chunk.id; draftOriginContent.value = chunk.content
}

async function saveChunk() {
  if (!chunkDraft.value.content.trim()) { message.warning(t('knowledgebaseDocumentDetail.fillChunkContentFirst')); return }
  isSavingChunk.value = true
  try {
    if (selectedChunkId.value) {
      await knowledgebaseApi.updateChunk(route.params.id, route.params.documentId, selectedChunkId.value, { content: chunkDraft.value.content })
      message.success(t('knowledgebaseDocumentDetail.chunkUpdated'))
    } else {
      await knowledgebaseApi.createChunk(route.params.id, route.params.documentId, { content: chunkDraft.value.content })
      message.success(t('knowledgebaseDocumentDetail.chunkCreated'))
    }
    await fetchDocumentDetail()
  } catch (error) { message.error(extractError(error, t('knowledgebaseDocumentDetail.saveChunkFailed'))) }
  finally { isSavingChunk.value = false }
}

async function deleteChunk(chunkId) {
  try {
    await knowledgebaseApi.deleteChunk(route.params.id, route.params.documentId, chunkId)
    message.success(t('knowledgebaseDocumentDetail.chunkDeleted'))
    await fetchDocumentDetail()
  } catch (error) { message.error(extractError(error, t('knowledgebaseDocumentDetail.deleteChunkFailed'))) }
}

function normalizeChunk(item) { return { id: item.id, content: item.content, preview: shortenText(item.content), length: item.content.length, token_count: item.token_count || 0 } }
function shortenText(text) { const n = (text || '').replace(/\s+/g, ' ').trim(); return n.length <= 92 ? n : n.slice(0, 92) + '...' }
function syncChunkPage(chunkId) { const i = chunks.value.findIndex(item => item.id === chunkId); if (i !== -1) chunkPage.value = Math.floor(i / CHUNKS_PER_PAGE) + 1 }

async function fetchDocumentDetail() {
  try {
    const [docResponse, chunkResponse] = await Promise.all([
      withReadinessRetry(() => knowledgebaseApi.getDocument(route.params.id, route.params.documentId)),
      withReadinessRetry(() => knowledgebaseApi.listChunks(route.params.id, route.params.documentId)),
    ])
    document.value = { id: docResponse.id, name: docResponse.original_name, status: docResponse.status }
    chunks.value = (chunkResponse.chunks || []).map(normalizeChunk)
    if (chunkPage.value > totalChunkPages.value) chunkPage.value = totalChunkPages.value
    if (chunks.value.length) {
      const current = chunks.value.find(item => item.id === selectedChunkId.value) || chunks.value[0]
      selectedChunkId.value = current.id; syncChunkPage(current.id)
      chunkDraft.value = { ...current }; draftOriginId.value = current.id; draftOriginContent.value = current.content
    } else {
      chunkPage.value = 1; selectedChunkId.value = ''; chunkDraft.value = { id: '', content: '' }
      draftOriginId.value = ''; draftOriginContent.value = ''
    }
  } catch (error) { message.error(extractError(error, t('knowledgebaseDocumentDetail.loadChunksFailed'))) }
}

function extractError(error, fallback) { return error?.response?.data?.detail?.error || error?.response?.data?.detail || error?.message || fallback }
onMounted(fetchDocumentDetail)
</script>

<style scoped>
/* Header */
.detail-header { display: flex; align-items: center; justify-content: space-between; margin-bottom: 20px; }
.detail-header-left { display: flex; align-items: center; gap: 12px; }
.back-btn {
  display: flex; align-items: center; justify-content: center;
  width: 32px; height: 32px; border: 1px solid #eaecf0; border-radius: 8px;
  background: #fff; cursor: pointer; color: #667085; transition: all 0.12s;
}
.back-btn:hover { border-color: #d0d5dd; color: var(--text-primary); }
.detail-title { font-size: 18px; font-weight: 600; margin: 0; }
.chunk-count-badge { font-size: 12px; padding: 2px 8px; border-radius: 6px; background: #f2f4f7; color: #667085; }

/* Layout */
.doc-layout { display: grid; grid-template-columns: minmax(300px, 380px) minmax(0, 1fr); gap: 20px; }

/* Chunk sidebar */
.chunk-sidebar {
  background: #fff; border: 1px solid #eaecf0; border-radius: 12px; padding: 12px;
  align-self: start; position: sticky; top: 16px;
}
.sidebar-header { display: flex; align-items: center; justify-content: space-between; padding: 4px 8px 12px; border-bottom: 1px solid #f2f4f7; margin-bottom: 8px; }
.sidebar-title { font-size: 11px; font-weight: 600; text-transform: uppercase; letter-spacing: 0.5px; color: #98a2b3; }
.add-btn {
  font-size: 12px; font-weight: 500; color: var(--primary); background: none; border: none;
  cursor: pointer; padding: 2px 6px; border-radius: 4px; transition: background 0.12s;
}
.add-btn:hover { background: var(--primary-light); }
.chunk-list { display: flex; flex-direction: column; gap: 6px; max-height: calc(100vh - 240px); overflow-y: auto; }
.chunk-item {
  padding: 10px 12px; border-radius: 8px; cursor: pointer; transition: all 0.12s;
  border: 1px solid transparent;
}
.chunk-item:hover { background: #f9fafb; }
.chunk-item.active { background: var(--primary-light); border-color: var(--primary); }
.chunk-item-top { display: flex; align-items: center; gap: 6px; margin-bottom: 4px; }
.chunk-id { font-size: 12px; font-weight: 600; color: #344054; }
.dirty-dot { width: 6px; height: 6px; border-radius: 50%; background: var(--warning); }
.chunk-len { font-size: 11px; color: #98a2b3; margin-left: auto; }
.chunk-preview { font-size: 12px; color: #667085; line-height: 1.5; margin: 0; display: -webkit-box; -webkit-line-clamp: 3; -webkit-box-orient: vertical; overflow: hidden; }
.sidebar-empty { padding: 40px 0; text-align: center; color: #98a2b3; font-size: 13px; }

/* Editor */
.chunk-editor { background: #fff; border: 1px solid #eaecf0; border-radius: 12px; padding: 20px; }
.editor-header { margin-bottom: 16px; }
.editor-title-row { display: flex; align-items: center; gap: 8px; margin-bottom: 6px; }
.editor-title { font-size: 15px; font-weight: 600; color: var(--text-primary); }
.status-badge { font-size: 11px; padding: 2px 8px; border-radius: 6px; font-weight: 500; }
.status-badge.dirty { background: #fef3cd; color: #b45309; }
.status-badge.synced { background: #f6ffed; color: #389e0d; }
.editor-meta { display: flex; align-items: center; gap: 12px; }
.meta-tag { font-size: 12px; padding: 1px 6px; border-radius: 4px; background: #f2f4f7; color: #667085; }
.char-count { font-size: 12px; color: #98a2b3; }
.editor-textarea :deep(textarea) { font-family: 'SF Mono', 'Fira Code', monospace; font-size: 13px; line-height: 1.6; }
.editor-footer { display: flex; align-items: center; justify-content: space-between; margin-top: 16px; }
.action-link { background: none; border: none; font-size: 12px; font-weight: 500; cursor: pointer; padding: 0; }
.action-link.danger { color: var(--error); }
.action-link.danger:hover { opacity: 0.7; }

@media (max-width: 900px) {
  .doc-layout { grid-template-columns: 1fr; }
  .chunk-sidebar { position: static; }
  .detail-header { flex-direction: column; align-items: flex-start; gap: 8px; }
}
@media (min-width: 901px) and (max-width: 1100px) {
  .doc-layout { grid-template-columns: minmax(260px, 320px) minmax(0, 1fr); }
}
</style>
